# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version=1.4.0
maven_group=com.bvengo
archivesBaseName=soundcontroller

# Versioning
## Fabric: https://fabricmc.net/develop
## ModMenu: https://maven.terraformersmc.com/com/terraformersmc/modmenu
modmenu_version=18.0.0-alpha.8
minecraft_version=26.1.2
loader_version=0.19.2

# Fabric API
fabric_api_version=0.148.0+26.1.2
